# Generated by Django 5.0.7 on 2024-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiatransportista',
            name='numero_guia',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
