# Generated by Django 5.0.7 on 2024-08-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guiatransportista_cantidad_guiatransportista_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_privilegiado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='guiatransportista',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
