# Generated by Django 5.0.7 on 2024-08-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_alter_guiatransportista_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulto',
        ),
    ]
