# Generated by Django 5.0.7 on 2024-08-17 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_bulto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiatransportista',
            name='numero_guia',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='El número de guía debe contener exactamente 5 dígitos numéricos', regex='^[0-9]{5}$')]),
        ),
    ]
