# Generated by Django 5.0.7 on 2024-08-17 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guiatransportista_numero_guia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('guia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.guiatransportista')),
            ],
        ),
    ]
